# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.closeButton = QtWidgets.QPushButton(self.graphicsView)
        self.closeButton.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.closeButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 9pt \"黑体\";\n"
"background-color: red;\n"
"")
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.controlTab = QtWidgets.QWidget()
        self.controlTab.setObjectName("controlTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controlTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraButton = QtWidgets.QPushButton(self.controlTab)
        self.cameraButton.setObjectName("cameraButton")
        self.verticalLayout.addWidget(self.cameraButton)
        self.autoDetectButton = QtWidgets.QPushButton(self.controlTab)
        self.autoDetectButton.setEnabled(False)
        self.autoDetectButton.setObjectName("autoDetectButton")
        self.verticalLayout.addWidget(self.autoDetectButton)
        self.manualDetectButton = QtWidgets.QPushButton(self.controlTab)
        self.manualDetectButton.setEnabled(False)
        self.manualDetectButton.setObjectName("manualDetectButton")
        self.verticalLayout.addWidget(self.manualDetectButton)
        self.textBrowser = QtWidgets.QTextBrowser(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.systemSettingsButton = QtWidgets.QPushButton(self.controlTab)
        self.systemSettingsButton.setObjectName("systemSettingsButton")
        self.verticalLayout.addWidget(self.systemSettingsButton)
        self.systemSettingsButton.raise_()
        self.autoDetectButton.raise_()
        self.manualDetectButton.raise_()
        self.textBrowser.raise_()
        self.cameraButton.raise_()
        self.tabWidget.addTab(self.controlTab, "")
        self.standerImageTab = QtWidgets.QWidget()
        self.standerImageTab.setObjectName("standerImageTab")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.standerImageTab)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.standerImageListWidget = QtWidgets.QListWidget(self.standerImageTab)
        self.standerImageListWidget.setObjectName("standerImageListWidget")
        self.verticalLayout1.addWidget(self.standerImageListWidget)
        self.addStanderImageButton = QtWidgets.QPushButton(self.standerImageTab)
        self.addStanderImageButton.setEnabled(False)
        self.addStanderImageButton.setObjectName("addStanderImageButton")
        self.verticalLayout1.addWidget(self.addStanderImageButton)
        self.removeStanderImageButton = QtWidgets.QPushButton(self.standerImageTab)
        self.removeStanderImageButton.setEnabled(False)
        self.removeStanderImageButton.setObjectName("removeStanderImageButton")
        self.verticalLayout1.addWidget(self.removeStanderImageButton)
        self.tabWidget.addTab(self.standerImageTab, "")
        self.settingTab = QtWidgets.QWidget()
        self.settingTab.setObjectName("settingTab")
        self.verticalLayout2 = QtWidgets.QVBoxLayout(self.settingTab)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.settingListWidget = QtWidgets.QListWidget(self.settingTab)
        self.settingListWidget.setObjectName("settingListWidget")
        self.verticalLayout2.addWidget(self.settingListWidget)
        self.label = QtWidgets.QLabel(self.settingTab)
        self.label.setObjectName("label")
        self.verticalLayout2.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.settingTab)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout2.addWidget(self.horizontalSlider)
        self.addSettingButton = QtWidgets.QPushButton(self.settingTab)
        self.addSettingButton.setObjectName("addSettingButton")
        self.verticalLayout2.addWidget(self.addSettingButton)
        self.tabWidget.addTab(self.settingTab, "")
        self.testImageTab = QtWidgets.QWidget()
        self.testImageTab.setObjectName("testImageTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.testImageTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.correctLabel = QtWidgets.QLabel(self.testImageTab)
        self.correctLabel.setObjectName("correctLabel")
        self.verticalLayout_2.addWidget(self.correctLabel)
        self.correctImageListWidget = QtWidgets.QListWidget(self.testImageTab)
        self.correctImageListWidget.setObjectName("correctImageListWidget")
        self.verticalLayout_2.addWidget(self.correctImageListWidget)
        self.correctImageButtonLayout = QtWidgets.QHBoxLayout()
        self.correctImageButtonLayout.setObjectName("correctImageButtonLayout")
        self.addCorrectImageButton = QtWidgets.QPushButton(self.testImageTab)
        self.addCorrectImageButton.setEnabled(False)
        self.addCorrectImageButton.setObjectName("addCorrectImageButton")
        self.correctImageButtonLayout.addWidget(self.addCorrectImageButton)
        self.importCorrectImageButton = QtWidgets.QPushButton(self.testImageTab)
        self.importCorrectImageButton.setEnabled(True)
        self.importCorrectImageButton.setObjectName("importCorrectImageButton")
        self.correctImageButtonLayout.addWidget(self.importCorrectImageButton)
        self.cleanCorrectImageListButton = QtWidgets.QPushButton(self.testImageTab)
        self.cleanCorrectImageListButton.setEnabled(True)
        self.cleanCorrectImageListButton.setObjectName("cleanCorrectImageListButton")
        self.correctImageButtonLayout.addWidget(self.cleanCorrectImageListButton)
        self.verticalLayout_2.addLayout(self.correctImageButtonLayout)
        self.errorLabel = QtWidgets.QLabel(self.testImageTab)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout_2.addWidget(self.errorLabel)
        self.errorImageListWidget = QtWidgets.QListWidget(self.testImageTab)
        self.errorImageListWidget.setObjectName("errorImageListWidget")
        self.verticalLayout_2.addWidget(self.errorImageListWidget)
        self.errorImageButtonLayout = QtWidgets.QHBoxLayout()
        self.errorImageButtonLayout.setObjectName("errorImageButtonLayout")
        self.addErrorImageButton = QtWidgets.QPushButton(self.testImageTab)
        self.addErrorImageButton.setEnabled(False)
        self.addErrorImageButton.setObjectName("addErrorImageButton")
        self.errorImageButtonLayout.addWidget(self.addErrorImageButton)
        self.importErrorImageButton = QtWidgets.QPushButton(self.testImageTab)
        self.importErrorImageButton.setEnabled(True)
        self.importErrorImageButton.setObjectName("importErrorImageButton")
        self.errorImageButtonLayout.addWidget(self.importErrorImageButton)
        self.cleanErrorImageListButton = QtWidgets.QPushButton(self.testImageTab)
        self.cleanErrorImageListButton.setEnabled(True)
        self.cleanErrorImageListButton.setObjectName("cleanErrorImageListButton")
        self.errorImageButtonLayout.addWidget(self.cleanErrorImageListButton)
        self.verticalLayout_2.addLayout(self.errorImageButtonLayout)
        self.batchDetectButton = QtWidgets.QPushButton(self.testImageTab)
        self.batchDetectButton.setObjectName("batchDetectButton")
        self.verticalLayout_2.addWidget(self.batchDetectButton)
        self.removeTestImageButton = QtWidgets.QPushButton(self.testImageTab)
        self.removeTestImageButton.setEnabled(False)
        self.removeTestImageButton.setObjectName("removeTestImageButton")
        self.verticalLayout_2.addWidget(self.removeTestImageButton)
        self.tabWidget.addTab(self.testImageTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.cameraAction = QtWidgets.QAction(MainWindow)
        self.cameraAction.setShortcut("")
        self.cameraAction.setProperty("shortcutVisibleInContextMenu", True)
        self.cameraAction.setObjectName("cameraAction")
        self.autoDetectAction = QtWidgets.QAction(MainWindow)
        self.autoDetectAction.setEnabled(False)
        self.autoDetectAction.setObjectName("autoDetectAction")
        self.manualDetectAction = QtWidgets.QAction(MainWindow)
        self.manualDetectAction.setEnabled(False)
        self.manualDetectAction.setObjectName("manualDetectAction")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ant Detector"))
        self.closeButton.setText(_translate("MainWindow", "关闭"))
        self.cameraButton.setText(_translate("MainWindow", "启动相机"))
        self.autoDetectButton.setText(_translate("MainWindow", "自动检测"))
        self.manualDetectButton.setText(_translate("MainWindow", "手动检测"))
        self.systemSettingsButton.setText(_translate("MainWindow", "系统设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controlTab), _translate("MainWindow", "控制"))
        self.addStanderImageButton.setText(_translate("MainWindow", "拍摄标准图"))
        self.removeStanderImageButton.setText(_translate("MainWindow", "删除标准图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.standerImageTab), _translate("MainWindow", "标准图"))
        self.label.setText(_translate("MainWindow", "笔刷粗度："))
        self.addSettingButton.setText(_translate("MainWindow", "添加检测设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingTab), _translate("MainWindow", "检测设置"))
        self.correctLabel.setText(_translate("MainWindow", "正确列表"))
        self.addCorrectImageButton.setText(_translate("MainWindow", "拍摄"))
        self.importCorrectImageButton.setText(_translate("MainWindow", "导入"))
        self.cleanCorrectImageListButton.setText(_translate("MainWindow", "清空"))
        self.errorLabel.setText(_translate("MainWindow", "错误列表"))
        self.addErrorImageButton.setText(_translate("MainWindow", "拍摄"))
        self.importErrorImageButton.setText(_translate("MainWindow", "导入"))
        self.cleanErrorImageListButton.setText(_translate("MainWindow", "清空"))
        self.batchDetectButton.setText(_translate("MainWindow", "批量检测"))
        self.removeTestImageButton.setText(_translate("MainWindow", "删除测试图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testImageTab), _translate("MainWindow", "测试图"))
        self.cameraAction.setText(_translate("MainWindow", "启动相机"))
        self.autoDetectAction.setText(_translate("MainWindow", "启动自动检测"))
        self.manualDetectAction.setText(_translate("MainWindow", "手动检测"))
        self.action_6.setText(_translate("MainWindow", "相机设置"))
        self.action_7.setText(_translate("MainWindow", "自动检测设置"))
