# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(230, 232)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingDialog.sizePolicy().hasHeightForWidth())
        SettingDialog.setSizePolicy(sizePolicy)
        self.formLayout = QtWidgets.QFormLayout(SettingDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SettingDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.titleEdit = QtWidgets.QLineEdit(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleEdit.sizePolicy().hasHeightForWidth())
        self.titleEdit.setSizePolicy(sizePolicy)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleEdit)
        self.label_2 = QtWidgets.QLabel(SettingDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.typeComboBox = QtWidgets.QComboBox(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeComboBox.sizePolicy().hasHeightForWidth())
        self.typeComboBox.setSizePolicy(sizePolicy)
        self.typeComboBox.setObjectName("typeComboBox")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.typeComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.typeComboBox)
        self.label_3 = QtWidgets.QLabel(SettingDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.argumentEdit = QtWidgets.QLineEdit(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.argumentEdit.sizePolicy().hasHeightForWidth())
        self.argumentEdit.setSizePolicy(sizePolicy)
        self.argumentEdit.setObjectName("argumentEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.argumentEdit)
        self.label_4 = QtWidgets.QLabel(SettingDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.thresholdEdit = QtWidgets.QLineEdit(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdEdit.sizePolicy().hasHeightForWidth())
        self.thresholdEdit.setSizePolicy(sizePolicy)
        self.thresholdEdit.setObjectName("thresholdEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.thresholdEdit)
        self.resetMaskButton = QtWidgets.QPushButton(SettingDialog)
        self.resetMaskButton.setObjectName("resetMaskButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.resetMaskButton)
        self.removeButton = QtWidgets.QPushButton(SettingDialog)
        self.removeButton.setObjectName("removeButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.removeButton)
        self.saveButton = QtWidgets.QPushButton(SettingDialog)
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.saveButton)
        self.label_5 = QtWidgets.QLabel(SettingDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.brushroughness = QtWidgets.QLineEdit(SettingDialog)
        self.brushroughness.setObjectName("brushroughness")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.brushroughness)

        self.retranslateUi(SettingDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Dialog"))
        self.label.setText(_translate("SettingDialog", "名称"))
        self.label_2.setText(_translate("SettingDialog", "类型"))
        self.typeComboBox.setItemText(0, _translate("SettingDialog", "模板检测"))
        self.typeComboBox.setItemText(1, _translate("SettingDialog", "灰度特征检测"))
        self.typeComboBox.setItemText(2, _translate("SettingDialog", "颜色特征检测"))
        self.typeComboBox.setItemText(3, _translate("SettingDialog", "灰度分布检测"))
        self.typeComboBox.setItemText(4, _translate("SettingDialog", "颜色分布检测"))
        self.label_3.setText(_translate("SettingDialog", "参数"))
        self.label_4.setText(_translate("SettingDialog", "阈值"))
        self.resetMaskButton.setText(_translate("SettingDialog", "重置检测区域"))
        self.removeButton.setText(_translate("SettingDialog", "删除"))
        self.saveButton.setText(_translate("SettingDialog", "保存"))
        self.label_5.setText(_translate("SettingDialog", "笔粗"))
