# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SystemSettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SystemSettingDialog(object):
    def setupUi(self, SystemSettingDialog):
        SystemSettingDialog.setObjectName("SystemSettingDialog")
        SystemSettingDialog.resize(297, 232)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SystemSettingDialog.sizePolicy().hasHeightForWidth())
        SystemSettingDialog.setSizePolicy(sizePolicy)
        self.formLayout = QtWidgets.QFormLayout(SystemSettingDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SystemSettingDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.external_Camera = QtWidgets.QRadioButton(SystemSettingDialog)
        self.external_Camera.setObjectName("external_Camera")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.external_Camera)
        self.computer_Camera = QtWidgets.QRadioButton(SystemSettingDialog)
        self.computer_Camera.setObjectName("computer_Camera")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.computer_Camera)
        self.label_2 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_5 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.saveButton = QtWidgets.QPushButton(SystemSettingDialog)
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.saveButton)
        self.external_signal = QtWidgets.QRadioButton(SystemSettingDialog)
        self.external_signal.setObjectName("external_signal")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.external_signal)
        self.internal_signal = QtWidgets.QRadioButton(SystemSettingDialog)
        self.internal_signal.setObjectName("internal_signal")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.internal_signal)
        self.trigger_settings = QtWidgets.QComboBox(SystemSettingDialog)
        self.trigger_settings.setObjectName("trigger_settings")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.trigger_settings)
        self.label_7 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(SystemSettingDialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.external_IP = QtWidgets.QLineEdit(SystemSettingDialog)
        self.external_IP.setObjectName("external_IP")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.external_IP)
        self.external_port = QtWidgets.QLineEdit(SystemSettingDialog)
        self.external_port.setObjectName("external_port")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.external_port)

        self.retranslateUi(SystemSettingDialog)
        QtCore.QMetaObject.connectSlotsByName(SystemSettingDialog)

    def retranslateUi(self, SystemSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SystemSettingDialog.setWindowTitle(_translate("SystemSettingDialog", "Dialog"))
        self.label.setText(_translate("SystemSettingDialog", "相机类型："))
        self.external_Camera.setText(_translate("SystemSettingDialog", "外设"))
        self.computer_Camera.setText(_translate("SystemSettingDialog", "本机"))
        self.label_2.setText(_translate("SystemSettingDialog", "界面风格："))
        self.label_3.setText(_translate("SystemSettingDialog", "自动检测感应器类型："))
        self.label_4.setText(_translate("SystemSettingDialog", "载入设置路径："))
        self.label_6.setText(_translate("SystemSettingDialog", "自动检测方式："))
        self.saveButton.setText(_translate("SystemSettingDialog", "保存"))
        self.external_signal.setText(_translate("SystemSettingDialog", "外部信号"))
        self.internal_signal.setText(_translate("SystemSettingDialog", "实时检测"))
        self.label_7.setText(_translate("SystemSettingDialog", "触发检测的设置："))
        self.label_8.setText(_translate("SystemSettingDialog", "外部设备IP："))
        self.label_9.setText(_translate("SystemSettingDialog", "外部设备端口："))

