# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_set_roi_model(object):
    def setupUi(self, set_roi_model):
        set_roi_model.setObjectName("set_roi_model")
        set_roi_model.resize(800, 600)
        self.widget = QtWidgets.QWidget(set_roi_model)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 521))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 781, 521))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.button_ok = QtWidgets.QPushButton(set_roi_model)
        self.button_ok.setGeometry(QtCore.QRect(670, 540, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.button_ok.setFont(font)
        self.button_ok.setObjectName("button_ok")
        self.button_clear = QtWidgets.QPushButton(set_roi_model)
        self.button_clear.setGeometry(QtCore.QRect(530, 540, 120, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.button_clear.setFont(font)
        self.button_clear.setObjectName("button_clear")

        self.retranslateUi(set_roi_model)
        QtCore.QMetaObject.connectSlotsByName(set_roi_model)

    def retranslateUi(self, set_roi_model):
        _translate = QtCore.QCoreApplication.translate
        set_roi_model.setWindowTitle(_translate("set_roi_model", "新建模型"))
        self.label.setText(_translate("set_roi_model", "TextLabel"))
        self.button_ok.setText(_translate("set_roi_model", "确定"))
        self.button_clear.setText(_translate("set_roi_model", "清除"))
